steps:
  - command: "script1.sh"
    key: "script1"

  - command: "script2.sh"
    key: "script2"
    depends_on: "script1"

  - command: "script3.sh"
    key: "script3"
    depends_on:
      - "script1"
      - "script2"
