steps:
  - group: "Some grouped steps" 
    steps:    
      - command: "scripts/sleep.sh"
        label: "Sleeping :stopwatch:"
        parallelism: 5
        agents:
          queue: $AGENTS
  - wait
  - command: "echo 'Group step complete'"
    label: "Group step complete 
    agents:
      queue: $AGENTS
